### ISSUE TITLE
Memory.copy(source: BytePointer, destination: BytePointer, length: Integer) in .kek

### ISSUE THREAD

**Issue by merskip** [merskip/kek-language#1]
**Purpose**
All should be in .kek

**TODO**
- [x] Parsing loop-while - `while (<condition>) { <code block> }`
- [x] Compiling loop-while
- [x] Implementation Memory.setValue(source: BytePointer, destination: BytePointer)

**Source code**
```
func Memory.copy(source: BytePointer, destination: BytePointer, length: Integer) {
   var i: Integer = 0
   while (i < length) {
      Memory.setValue(source + i, destination + i)
      i = i + 1
   }
}
```
