### ISSUE TITLE
Add operator definiction

### ISSUE THREAD

**Issue by merskip** [merskip/kek-language#10]
**TODO**

- [x] Parsing operator keyword
- [x] Parsing operator definiction like function definiction
- [x] Compile operator definiction

**Example source code**

```
operator := (lhs: BytePointer, rhs: BytePointer) -> Void {
    lhs.setValue(rhs)
}
```

**EBNF**

```ebnf
operator-declaration ::= modifiers "operator" operator "(" function-parameters ")" "{" code-block "}"
```
