### ISSUE TITLE
Language feature: data (aka struct)

### ISSUE THREAD

**Issue by merskip** [merskip/kek-language#3]
**TODO**

- [x] Parsing data type declaration
- [x] Compiling data type declaration
- [x] Generate default constructor

**Example source code**

```
data String(
   guts: BytePointer,
   length: Integer
)
```

**EBNF**

```ebnf
data-type-declaration ::= "data" type-identifier "(" data-type-body ")"
data-type-body ::= [data-type-fields]
data-type-fields ::= data-type-field | data-type-field "," data-type-fields
data-type-field ::= "var" identifier ":" type-identifier
```
