### ISSUE TITLE
Adding deallocation to types

### ISSUE THREAD

**Issue by merskip** [merskip/kek-language#5]
**Purpose**

When two Strings are concatenated, there need is to allocate dynamic memory. This means the allocated memory should be free when isn't any longer needed. A user shouldn't do that manually.

String type is a wrapper for byte pointer of the character sequence. There are two situations:
1. String is a wrapper of "global string" and there isn't a need for free memory
2. String is a wrapper of a newly created string (eg. by concatenation) and in this case, the memory must be free

**TODO**

- [ ] Performing `deinit`/`dealloc`/.etc when a variable leave an own scope
- [ ] Adding that to String and deallocate created String instance
- [ ] Adding maybe flag `immortal` to String if the String is "global string"

**Example source code**

```
func String.deallocate() {
   if (!immortal) {
      Memory.free(guts)
   }
}
```
